export default {
  CACHE_CONTROL: process.env.NEXT_PUBLIC_CACHE_CONTROL || '',
  ACTIVITIES_APP_URL: process.env.NEXT_PUBLIC_ACTIVITIES_APP_URL,
  ACTIVITIES_API_URL: process.env.NEXT_PUBLIC_ACTIVITIES_API_URL,
} as {
  CACHE_CONTROL: string;
  ACTIVITIES_APP_URL: string;
  ACTIVITIES_API_URL: string;
}
