import * as React from 'react';
import Head from 'next/head';

function Metadata({ title }) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
};

export default Metadata;
