import type { NextPage } from 'next'
import { Space, Layout, Typography } from 'antd'
import Head from 'next/head'
import { Fragment } from 'react'

import styles from '../styles/Home.module.scss'
// import variables from '../styles/variables.module.scss';

const { Content } = Layout;
const { Title } = Typography;

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Atividades</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Content className={styles.pageContent}>
          <Space className={styles.container}>
            <Title>Atividades</Title>
          </Space>
        </Content>
      </Layout>
    </Fragment>
  )
}

export default Home
